# Generated by Django 3.0.5 on 2021-01-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('Kepemimpinan', 'Kepemimpinan'), ('Keagamaan', 'Keagamaan'), ('Kesenian', 'Kesenian'), ('Olahraga', 'Olahraga'), ('Lain-Lain', 'Lain-Lain')], max_length=255, verbose_name='Jenis Ekskul')),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('singkat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nama Singkat')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII'), ('9', 'IX'), ('10', 'X'), ('11', 'XI'), ('12', 'XII'), ('13', 'XIII')], max_length=3)),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('nama', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KKM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.SmallIntegerField(default=0, verbose_name='KKM Pengetahuan')),
                ('keterampilan', models.SmallIntegerField(default=0, verbose_name='KKM Keterampilan')),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Mata Pelajaran')),
                ('singkat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nama Singkat Mata Pelajaran')),
                ('kelompok', models.CharField(choices=[('NA', 'Normatif Adaptif'), ('WS', 'Kejuruan'), ('MULOK', 'Muatan Lokal')], max_length=5, verbose_name='Kelompok Mata Pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tingkat', models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('SMK', 'Sekolah Menengah Kejuruan')], max_length=3, verbose_name='Tingkat Sekolah')),
                ('npsn', models.CharField(max_length=8)),
                ('alamat', models.CharField(max_length=255)),
                ('kode_pos', models.CharField(max_length=5)),
                ('no_telepon', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('kelurahan', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50, verbose_name='Kota/Kabupaten')),
                ('provinsi', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('kepsek', models.CharField(max_length=255, null=True, verbose_name='Kepala Sekolah')),
                ('nip_kepsek', models.CharField(max_length=18, null=True, verbose_name='Nomor Induk')),
            ],
            options={
                'verbose_name': 'Informasi Sekolah',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(editable=False, max_length=255, null=True)),
                ('tahun_mulai', models.CharField(max_length=4, verbose_name='Tahun Mulai')),
                ('tahun_akhir', models.CharField(max_length=4, verbose_name='Tahun Berakhir')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor', models.TextField(null=True, verbose_name='Lokasi PDF Rapor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='sekolah.Semester')),
            ],
        ),
    ]
