# Generated by Django 3.0.5 on 2021-01-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='siswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='siswa.Siswa'),
        ),
        migrations.AddField(
            model_name='kkm',
            name='matapelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.MataPelajaran'),
        ),
        migrations.AddField(
            model_name='kkm',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.Semester'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.Jurusan'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='matapelajaran',
            field=models.ManyToManyField(blank=True, related_name='kelas', to='sekolah.MataPelajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.Semester'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='walikelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas', to=settings.AUTH_USER_MODEL),
        ),
    ]
