# Generated by Django 3.1.4 on 2020-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanggalPendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_mulai', models.CharField(max_length=4, verbose_name='Tahun Mulai')),
                ('tahun_akhir', models.CharField(max_length=4, verbose_name='Tahun Berakhir')),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
    ]
