# Generated by Django 3.1.4 on 2020-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_tanggalpendidikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanggalpendidikan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
