# Generated by Django 3.0.5 on 2021-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_auto_20210109_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=3),
        ),
    ]
