# Generated by Django 3.1.4 on 2020-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_tanggalpendidikan_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('singkat', models.CharField(max_length=10, verbose_name='Nama Singkat')),
            ],
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='tingkat',
            field=models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('SMK', 'Sekolah Menengah Kejuruan')], max_length=3, verbose_name='Tingkat Sekolah'),
        ),
        migrations.AlterField(
            model_name='tanggalpendidikan',
            name='semester',
            field=models.CharField(choices=[('1', 'Ganjil'), ('2', 'Genap')], max_length=1),
        ),
    ]
