# Generated by Django 3.1.4 on 2020-12-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_auto_20201215_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Mata Pelajaran')),
                ('singkat', models.CharField(max_length=20, verbose_name='Nama Singkat Mata Pelajaran')),
                ('kelompok', models.CharField(choices=[('NA', 'Normatif Adaptif'), ('WS', 'Workshop'), ('MULOK', 'Muatan Lokal')], max_length=5, verbose_name='Kelompok Mata Pelajaran')),
            ],
        ),
        migrations.RenameField(
            model_name='jurusan',
            old_name='lengkap',
            new_name='nama',
        ),
    ]
