# Generated by Django 3.0.5 on 2021-01-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_auto_20210110_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='singkat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Nama Singkat Mata Pelajaran'),
        ),
    ]
