# Generated by Django 3.0.5 on 2021-01-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_auto_20210111_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='tingkat_verbose',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Tingkat Sekolah (Lengkap)'),
        ),
    ]
