# Generated by Django 3.0.5 on 2021-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_sekolah_tingkat_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='tingkat_verbose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tingkat Sekolah (Lengkap)'),
        ),
    ]
