# Generated by Django 3.1.4 on 2020-12-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_auto_20201215_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='keterampilan',
            field=models.SmallIntegerField(verbose_name='KKM Keterampilan'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='pengetahuan',
            field=models.SmallIntegerField(verbose_name='KKM Pengetahuan'),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('7', 'VII'), ('8', 'VIII'), ('9', 'IX')], max_length=2)),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('angkatan', models.CharField(max_length=3)),
                ('jurusan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sekolah.jurusan')),
            ],
        ),
    ]
