# Generated by Django 3.0.5 on 2021-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_auto_20210115_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
