# Generated by Django 3.1.4 on 2020-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_auto_20201215_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tingkat',
            name='tingkat',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
