# Generated by Django 3.0.5 on 2021-02-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_rapor_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_mulai', models.CharField(max_length=4, verbose_name='Tahun Mulai')),
                ('tahun_akhir', models.CharField(max_length=4, verbose_name='Tahun Berakhir')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='tahun_akhir',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='tahun_mulai',
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='tahunpelajaran',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='sekolah.TahunPelajaran'),
            preserve_default=False,
        ),
    ]
