# Generated by Django 3.1.4 on 2020-12-14 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0009_auto_20201215_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='matapelajaran',
            field=models.ManyToManyField(related_name='kelas', to='sekolah.MataPelajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='walikelas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.jurusan'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='tingkat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.tingkat'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='matapelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.matapelajaran'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='tgl_pendidikan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.tanggalpendidikan'),
        ),
    ]
