# Generated by Django 3.1.4 on 2020-12-15 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0010_auto_20201215_0231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TanggalPendidikan',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='kkm',
            old_name='tgl_pendidikan',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='kelas',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.jurusan'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='matapelajaran',
            field=models.ManyToManyField(blank=True, related_name='kelas', to='sekolah.MataPelajaran'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='walikelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas', to=settings.AUTH_USER_MODEL),
        ),
    ]
