# Generated by Django 3.1.4 on 2020-12-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0011_auto_20201215_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.semester'),
        ),
    ]
