# Generated by Django 3.1.4 on 2020-12-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0012_auto_20201215_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='angkatan',
        ),
    ]
