# Generated by Django 3.1.4 on 2020-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0016_auto_20201221_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='alamat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=6),
        ),
    ]
