# Generated by Django 3.1.4 on 2020-12-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0017_auto_20201230_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='nama',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
