# Generated by Django 3.1.4 on 2020-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0018_semester_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('Kepemimpinan', 'Kepemimpinan'), ('Keagamaan', 'Keagamaan'), ('Kesenian', 'Kesenian'), ('Olahraga', 'Olahraga'), ('Lain-Lain', 'Lain-Lain')], max_length=255, verbose_name='Jenis Ekskul')),
            ],
        ),
    ]
