# Generated by Django 3.1.4 on 2021-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0019_ekskul'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='nama',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
