# Generated by Django 3.1.4 on 2021-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0020_kelas_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='keterampilan',
            field=models.SmallIntegerField(default=0, verbose_name='KKM Keterampilan'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='pengetahuan',
            field=models.SmallIntegerField(default=0, verbose_name='KKM Pengetahuan'),
        ),
    ]
