# Generated by Django 3.1.4 on 2021-01-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0011_auto_20210103_1803'),
        ('sekolah', '0021_auto_20210106_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='sekolah.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='siswa.siswa')),
            ],
        ),
    ]
