# Generated by Django 3.1.4 on 2021-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0022_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='singkat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nama Singkat'),
        ),
    ]
