# Generated by Django 3.1.4 on 2021-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0024_auto_20210108_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=3),
        ),
    ]
