# Generated by Django 3.1.4 on 2021-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0025_auto_20210108_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='rapor',
            field=models.TextField(editable=False, null=True, verbose_name='Lokasi PDF Rapor'),
        ),
    ]
