# Generated by Django 3.1.4 on 2021-01-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0026_rapor_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='rapor',
            field=models.TextField(null=True, verbose_name='Lokasi PDF Rapor'),
        ),
    ]
