# Generated by Django 3.0.5 on 2021-01-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Siswa')),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('nis', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], default='P', max_length=1, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('sekolah_asal', models.CharField(max_length=255)),
                ('diterima_di_tingkat', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII'), ('9', 'IX'), ('10', 'X'), ('11', 'XI'), ('12', 'XII'), ('13', 'XIII')], max_length=3)),
                ('nama_ayah', models.CharField(max_length=255)),
                ('nama_ibu', models.CharField(max_length=255)),
                ('nama_wali', models.CharField(blank=True, max_length=255, null=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='sekolah.Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiEkskul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.Ekskul')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_ekskul', to='sekolah.Semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekskul', to='siswa.Siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.PositiveSmallIntegerField()),
                ('keterampilan', models.PositiveSmallIntegerField()),
                ('matapelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.MataPelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.Semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='siswa.Siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izin', models.PositiveSmallIntegerField(default=0)),
                ('sakit', models.PositiveSmallIntegerField(default=0)),
                ('bolos', models.PositiveSmallIntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='sekolah.Semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='siswa.Siswa')),
            ],
        ),
    ]
