# Generated by Django 3.1.4 on 2020-12-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0013_remove_kelas_angkatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Siswa')),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('nis', models.CharField(max_length=9, unique=True)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], default='P', max_length=1, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(max_length=255)),
                ('anak_ke', models.SmallIntegerField()),
                ('alamat', models.TextField()),
                ('sekolah_asal', models.CharField(max_length=255)),
                ('nama_ayah', models.CharField(max_length=255)),
                ('nama_ibu', models.CharField(max_length=255)),
                ('nama_wali', models.CharField(blank=True, max_length=255, null=True)),
                ('diterima_di_tingkat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.tingkat')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sekolah.kelas')),
            ],
        ),
    ]
