# Generated by Django 3.1.4 on 2020-12-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0013_remove_kelas_angkatan'),
        ('siswa', '0002_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='matapelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.matapelajaran'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='semester',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.semester'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='siswa.siswa'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='diterima_di_tingkat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='sekolah.tingkat'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='sekolah.kelas'),
        ),
    ]
