# Generated by Django 3.0.5 on 2021-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_auto_20210109_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='diterima_di_tingkat',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII'), ('9', 'IX'), ('10', 'X'), ('11', 'XI'), ('12', 'XII'), ('13', 'XIII')], max_length=3),
        ),
    ]
