# Generated by Django 3.0.5 on 2021-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_auto_20210110_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='diterima_di_tingkat',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=3),
        ),
    ]
