# Generated by Django 3.0.5 on 2021-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0013_auto_20210309_1032'),
        ('siswa', '0004_auto_20210218_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas',
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ManyToManyField(blank=True, related_name='siswa', to='sekolah.Kelas'),
        ),
    ]
