# Generated by Django 3.1.4 on 2020-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_auto_20201216_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
