# Generated by Django 3.1.4 on 2020-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_siswa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
