# Generated by Django 3.0.5 on 2021-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_auto_20210310_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=10),
        ),
    ]
