# Generated by Django 3.1.4 on 2020-12-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0016_auto_20201221_1745'),
        ('siswa', '0007_auto_20201222_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='sekolah.semester'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='anak_ke',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
