# Generated by Django 3.1.4 on 2021-01-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0019_ekskul'),
        ('siswa', '0008_auto_20201222_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiEkskul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sekolah.ekskul')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_ekskul', to='sekolah.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekskul', to='siswa.siswa')),
            ],
        ),
    ]
