# Generated by Django 3.1.4 on 2021-01-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0020_kelas_nama'),
        ('siswa', '0009_nilaiekskul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='sekolah.kelas'),
        ),
    ]
