# Generated by Django 3.1.4 on 2021-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0010_auto_20210103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='bolos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='izin',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='sakit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
