# Generated by Django 3.1.4 on 2021-01-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0011_auto_20210103_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='anak_ke',
        ),
    ]
