# Generated by Django 3.1.4 on 2021-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0012_remove_siswa_anak_ke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='diterima_di_tingkat',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
