# Generated by Django 3.0.5 on 2021-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nip', models.CharField(max_length=18, unique=True, verbose_name='Nomor Induk')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], default='P', max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('agama', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_walikelas', models.BooleanField(default=True, verbose_name='Walikelas')),
                ('is_staftu', models.BooleanField(default=True, verbose_name='Staf TU')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
