# Generated by Django 3.1.4 on 2020-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_guru_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='agama',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guru',
            name='alamat',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guru',
            name='tanggal_lahir',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guru',
            name='tempat_lahir',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
