# Generated by Django 3.1.4 on 2020-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_auto_20201216_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='agama',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='tempat_lahir',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
