# Generated by Django 3.0.5 on 2021-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_auto_20210308_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gelar',
            old_name='verbose_gelar',
            new_name='verbose_tingkat',
        ),
        migrations.AddField(
            model_name='gelar',
            name='gelar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='nama_gelar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gelar',
            name='tingkat_gelar',
            field=models.CharField(choices=[('A.P.', 'Diploma 1'), ('A.Ma.', 'Diploma 2'), ('A.Md.', 'Diploma 3'), ('A.', 'Diploma 4'), ('S.', 'Sarjana'), ('M.', 'Magister'), ('Dr.', 'Doktor')], max_length=5),
        ),
    ]
