# Generated by Django 3.0.5 on 2021-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_auto_20210308_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/guru/'),
        ),
    ]
