# Generated by Django 3.1.4 on 2020-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_auto_20201216_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='alamat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
