# Generated by Django 3.1.4 on 2020-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0005_auto_20201216_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
