# Generated by Django 3.0.5 on 2021-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0007_auto_20210316_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
